[2025-09-20T18:58:48.318+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-20T18:58:48.358+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts_optimized.extract_load_fact_Invoices scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T18:58:48.376+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts_optimized.extract_load_fact_Invoices scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2025-09-20T18:58:48.377+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 3
[2025-09-20T18:58:48.400+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_load_fact_Invoices> on 2024-01-01 00:00:00+00:00
[2025-09-20T18:58:48.405+0000] {standard_task_runner.py:72} INFO - Started process 153 to run task
[2025-09-20T18:58:48.411+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bronze_full_load_spaceparts_optimized', 'extract_load_fact_Invoices', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/01_Bronce.py', '--cfg-path', '/tmp/tmp13ogyef_']
[2025-09-20T18:58:48.414+0000] {standard_task_runner.py:105} INFO - Job 162: Subtask extract_load_fact_Invoices
[2025-09-20T18:58:48.756+0000] {task_command.py:467} INFO - Running <TaskInstance: bronze_full_load_spaceparts_optimized.extract_load_fact_Invoices scheduled__2024-01-01T00:00:00+00:00 [running]> on host 050d5b6b4fc2
[2025-09-20T18:58:48.931+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='bronze_full_load_spaceparts_optimized' AIRFLOW_CTX_TASK_ID='extract_load_fact_Invoices' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2025-09-20T18:58:48.934+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-20T18:58:48.951+0000] {01_Bronce.py:385} INFO - Starting optimized extraction for table: fact.Invoices
[2025-09-20T18:58:52.315+0000] {01_Bronce.py:398} INFO - Table fact.Invoices has 18,459,441 rows
[2025-09-20T18:58:52.316+0000] {01_Bronce.py:420} INFO - Using chunk size: 15,000 for 18,459,441 rows
[2025-09-20T18:58:52.317+0000] {01_Bronce.py:425} INFO - Starting streaming extraction and load for fact.Invoices
[2025-09-20T18:58:56.083+0000] {01_Bronce.py:235} INFO - Processing chunk 1 with 15000 rows
[2025-09-20T18:58:56.110+0000] {01_Bronce.py:298} ERROR - Error creating table bronze_fact_invoices: 'Connection' object has no attribute 'commit'
[2025-09-20T18:58:56.110+0000] {01_Bronce.py:360} ERROR - Error in streaming load to bronze_fact_invoices: 'Connection' object has no attribute 'commit'
[2025-09-20T18:58:56.110+0000] {01_Bronce.py:445} ERROR - Error processing table fact.Invoices: 'Connection' object has no attribute 'commit'
[2025-09-20T18:58:56.129+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/01_Bronce.py", line 427, in extract_and_load_table_optimized
    records_loaded = loader.load_data_streaming(data_iterator, bronze_table_name)
  File "/opt/airflow/dags/01_Bronce.py", line 343, in load_data_streaming
    column_mapping = self.create_table_if_not_exists(chunk, table_name)
  File "/opt/airflow/dags/01_Bronce.py", line 292, in create_table_if_not_exists
    conn.commit()
AttributeError: 'Connection' object has no attribute 'commit'
[2025-09-20T18:58:56.142+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=bronze_full_load_spaceparts_optimized, task_id=extract_load_fact_Invoices, run_id=scheduled__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20250920T185848, end_date=20250920T185856
[2025-09-20T18:58:56.195+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-20T18:58:56.196+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 162 for task extract_load_fact_Invoices ('Connection' object has no attribute 'commit'; 153)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/01_Bronce.py", line 427, in extract_and_load_table_optimized
    records_loaded = loader.load_data_streaming(data_iterator, bronze_table_name)
  File "/opt/airflow/dags/01_Bronce.py", line 343, in load_data_streaming
    column_mapping = self.create_table_if_not_exists(chunk, table_name)
  File "/opt/airflow/dags/01_Bronce.py", line 292, in create_table_if_not_exists
    conn.commit()
AttributeError: 'Connection' object has no attribute 'commit'
[2025-09-20T18:58:56.232+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-20T18:58:56.284+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-20T18:58:56.286+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
